import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { TopBar } from '@/components/Topbar';
import { AnnouncementBar } from '@/components/AnnouncementBar';
import Footer from '@/components/Footer';
import { CTASection } from '@/components/CTA';

const inter = Inter({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </head>
      <body className={inter.className + ' pt-[32px]'}>
        <header>
          <AnnouncementBar />
          <TopBar />
        </header>
        {children}

        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
